In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [5]:
arr=np.array(l) # Converting list into numpy arrary

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1=np.array([[1,2,3],[2,3,4]])

In [12]:
type(arr1)

numpy.ndarray

In [13]:
arr1.ndim

2

In [14]:
np.matrix([[1,2,3,4,5,4],[8,3,4,5,6,8]])

matrix([[1, 2, 3, 4, 5, 4],
        [8, 3, 4, 5, 6, 8]])

In [15]:
mat=np.matrix(l)

In [16]:
mat

matrix([[1, 2, 3, 4, 5]])

In [17]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [21]:
(i for i in range(5))

<generator object <genexpr> at 0x000002530E816F20>

In [22]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [23]:
iterable=(i*i for i in range(5))

In [24]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [25]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [28]:
arr1.ndim

2

In [29]:
arr1.size

6

In [30]:
arr1.shape

(2, 3)

In [31]:
arr.dtype

dtype('int32')

In [32]:
range(5)

range(0, 5)

In [33]:
list(range(5))

[0, 1, 2, 3, 4]

In [35]:
list(np.arange(.4,10.4))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [36]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [38]:
list(np.logspace(1,5,10))

[10.0,
 27.825594022071243,
 77.4263682681127,
 215.44346900318823,
 599.4842503189409,
 1668.100537200059,
 4641.588833612777,
 12915.496650148827,
 35938.13663804626,
 100000.0]

In [39]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
np.zeros((3,4,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [43]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
arr=np.ones((3,4))

In [46]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [48]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [49]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
arr1=np.eye(5)

In [52]:
import pandas as pd

In [53]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [54]:
np.random.rand(2,3)

array([[0.48860294, 0.88605111, 0.54362059],
       [0.2098478 , 0.94319333, 0.66211103]])

In [55]:
np.random.randn(2,3)

array([[-0.8844607 ,  0.15676468,  1.02491228],
       [ 1.02589529, -0.0110644 , -1.05091882]])

In [57]:
arr2=np.random.randint(1,5,(3,4))

In [58]:
arr2.size

12

In [59]:
arr2.shape

(3, 4)

In [60]:
arr2

array([[4, 1, 4, 3],
       [1, 4, 4, 3],
       [3, 2, 3, 2]])

In [61]:
arr2.reshape(6,2)

array([[4, 1],
       [4, 3],
       [1, 4],
       [4, 3],
       [3, 2],
       [3, 2]])

In [63]:
arr2.reshape(4,-1)

array([[4, 1, 4],
       [3, 1, 4],
       [4, 3, 3],
       [2, 3, 2]])

In [65]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[1]]],


         [[[4]]]],



        [[[[3]]],


         [[[1]]],


         [[[4]]]]],




       [[[[[4]]],


         [[[3]]],


         [[[3]]]],



        [[[[2]]],


         [[[3]]],


         [[[2]]]]]])

In [66]:
arr3=np.random.randint(1,10,(5,6))

In [67]:
arr3

array([[5, 1, 1, 4, 7, 5],
       [6, 3, 9, 1, 2, 4],
       [7, 4, 6, 8, 6, 5],
       [1, 4, 7, 4, 9, 5],
       [9, 7, 9, 7, 1, 6]])

In [68]:
arr3>8

array([[False, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [ True, False,  True, False, False, False]])

In [69]:
arr3[arr3>8]

array([9, 9, 9, 9])