In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr=np.array(l) # Converting list into numpy arrary

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([[1,2,3],[2,3,4]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.ndim

2

In [11]:
np.matrix([[1,2,3,4,5,4],[8,3,4,5,6,8]])

matrix([[1, 2, 3, 4, 5, 4],
        [8, 3, 4, 5, 6, 8]])

In [12]:
mat=np.matrix(l)

In [13]:
mat

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [17]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [18]:
(i for i in range(5))

<generator object <genexpr> at 0x000001953E463440>

In [19]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [20]:
iterable=(i*i for i in range(5))

In [21]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [25]:
arr1.ndim

2

In [26]:
arr1.size

6

In [27]:
arr1.shape

(2, 3)

In [28]:
arr.dtype

dtype('int32')

In [29]:
range(5)

range(0, 5)

In [30]:
list(range(5))

[0, 1, 2, 3, 4]

In [31]:
list(np.arange(.4,10.4))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [32]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [33]:
list(np.logspace(1,5,10))

[10.0,
 27.825594022071243,
 77.4263682681127,
 215.44346900318823,
 599.4842503189409,
 1668.100537200059,
 4641.588833612777,
 12915.496650148827,
 35938.13663804626,
 100000.0]

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
np.zeros((3,4,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
arr=np.ones((3,4))

In [40]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [42]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [43]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
arr1=np.eye(5)

In [46]:
import pandas as pd

In [47]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [48]:
np.random.rand(2,3)

array([[0.8074109 , 0.13506389, 0.42955747],
       [0.08202113, 0.88639139, 0.99677715]])

In [49]:
np.random.randn(2,3)

array([[ 0.48220387,  0.45216942, -0.1261535 ],
       [ 1.6479845 ,  1.13159136,  0.68736595]])

In [50]:
arr2=np.random.randint(1,5,(3,4))

In [51]:
arr2.size

12

In [52]:
arr2.shape

(3, 4)

In [53]:
arr2

array([[4, 3, 2, 4],
       [1, 2, 4, 1],
       [3, 2, 1, 2]])

In [54]:
arr2.reshape(6,2)

array([[4, 3],
       [2, 4],
       [1, 2],
       [4, 1],
       [3, 2],
       [1, 2]])

In [55]:
arr2.reshape(4,-1)

array([[4, 3, 2],
       [4, 1, 2],
       [4, 1, 3],
       [2, 1, 2]])

In [56]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[3]]],


         [[[2]]]],



        [[[[4]]],


         [[[1]]],


         [[[2]]]]],




       [[[[[4]]],


         [[[1]]],


         [[[3]]]],



        [[[[2]]],


         [[[1]]],


         [[[2]]]]]])

In [57]:
arr3=np.random.randint(1,10,(5,6))

In [58]:
arr3

array([[1, 2, 4, 8, 5, 1],
       [6, 6, 2, 1, 7, 5],
       [2, 2, 5, 5, 5, 2],
       [8, 4, 8, 9, 7, 9],
       [7, 8, 4, 4, 4, 4]])

In [59]:
arr3>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False,  True],
       [False, False, False, False, False, False]])

In [60]:
arr3[arr3>8]

array([9, 9])

In [61]:
arr3[0]

array([1, 2, 4, 8, 5, 1])

In [62]:
arr1[0,[0,1]]

array([1., 0.])

In [63]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
arr3

array([[1, 2, 4, 8, 5, 1],
       [6, 6, 2, 1, 7, 5],
       [2, 2, 5, 5, 5, 2],
       [8, 4, 8, 9, 7, 9],
       [7, 8, 4, 4, 4, 4]])

In [71]:
arr3[0][0:4]

array([1, 2, 4, 8])

In [72]:
arr3

array([[1, 2, 4, 8, 5, 1],
       [6, 6, 2, 1, 7, 5],
       [2, 2, 5, 5, 5, 2],
       [8, 4, 8, 9, 7, 9],
       [7, 8, 4, 4, 4, 4]])

In [73]:
arr3[2:4]

array([[2, 2, 5, 5, 5, 2],
       [8, 4, 8, 9, 7, 9]])

In [74]:
arr3[2:4,[2,3]]

array([[5, 5],
       [8, 9]])

In [75]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [76]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [77]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [78]:
arr1+arr2

array([[3, 2, 3],
       [4, 3, 3],
       [3, 3, 4]])

In [79]:
arr2*arr2

array([[1, 1, 1],
       [4, 4, 4],
       [4, 1, 4]])

In [80]:
arr1-arr2

array([[ 1,  0,  1],
       [ 0, -1, -1],
       [-1,  1,  0]])

In [81]:
arr1@arr2

array([[8, 6, 8],
       [6, 5, 6],
       [9, 7, 9]])

In [82]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [83]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [2, 1, 2]])

In [84]:
arr=np.zeros((3,4))

In [85]:
arr+4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [86]:
a=np.array([1,2,3,4])

In [87]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [91]:
b=np.array([3,4,5,6])

In [92]:
arr+b

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [93]:
arr+b.T

array([[3., 4., 5., 6.],
       [3., 4., 5., 6.],
       [3., 4., 5., 6.]])

In [94]:
np.sqrt(arr)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
arr1

array([[2, 1, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [97]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356]])

In [98]:
np.log10(arr1)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.30103]])

In [99]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 7.3890561 ]])

In [100]:
np.min(arr1)

1

In [101]:
np.max(arr1)

2