In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
arr=np.array(l) # Converting list into numpy arrary

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([[1,2,3],[2,3,4]])

In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.ndim

2

In [11]:
np.matrix([[1,2,3,4,5,4],[8,3,4,5,6,8]])

matrix([[1, 2, 3, 4, 5, 4],
        [8, 3, 4, 5, 6, 8]])

In [12]:
mat=np.matrix(l)

In [13]:
mat

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [17]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [18]:
(i for i in range(5))

<generator object <genexpr> at 0x000001CB56180040>

In [19]:
list((i for i in range(5)))

[0, 1, 2, 3, 4]

In [20]:
iterable=(i*i for i in range(5))

In [21]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [22]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [25]:
arr1.ndim

2

In [26]:
arr1.size

6

In [27]:
arr1.shape

(2, 3)

In [28]:
arr.dtype

dtype('int32')

In [29]:
range(5)

range(0, 5)

In [30]:
list(range(5))

[0, 1, 2, 3, 4]

In [31]:
list(np.arange(.4,10.4))

[0.4,
 1.4,
 2.4,
 3.3999999999999995,
 4.3999999999999995,
 5.3999999999999995,
 6.3999999999999995,
 7.3999999999999995,
 8.399999999999999,
 9.399999999999999]

In [32]:
np.linspace(1,2,20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

In [33]:
list(np.logspace(1,5,10))

[10.0,
 27.825594022071243,
 77.4263682681127,
 215.44346900318823,
 599.4842503189409,
 1668.100537200059,
 4641.588833612777,
 12915.496650148827,
 35938.13663804626,
 100000.0]

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.zeros((3,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
np.zeros((3,4,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
arr=np.ones((3,4))

In [40]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [42]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [43]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
arr1=np.eye(5)

In [46]:
import pandas as pd

In [47]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [48]:
np.random.rand(2,3)

array([[0.7012556 , 0.72065283, 0.87250167],
       [0.84236722, 0.59912511, 0.53927745]])

In [49]:
np.random.randn(2,3)

array([[ 0.20849513,  1.79560667, -0.129706  ],
       [ 0.5531056 ,  0.79005483,  1.58215003]])

In [50]:
arr2=np.random.randint(1,5,(3,4))

In [51]:
arr2.size

12

In [52]:
arr2.shape

(3, 4)

In [53]:
arr2

array([[3, 3, 2, 2],
       [1, 4, 2, 4],
       [2, 4, 2, 3]])

In [54]:
arr2.reshape(6,2)

array([[3, 3],
       [2, 2],
       [1, 4],
       [2, 4],
       [2, 4],
       [2, 3]])

In [55]:
arr2.reshape(4,-1)

array([[3, 3, 2],
       [2, 1, 4],
       [2, 4, 2],
       [4, 2, 3]])

In [56]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[3]]],


         [[[3]]],


         [[[2]]]],



        [[[[2]]],


         [[[1]]],


         [[[4]]]]],




       [[[[[2]]],


         [[[4]]],


         [[[2]]]],



        [[[[4]]],


         [[[2]]],


         [[[3]]]]]])

In [57]:
arr3=np.random.randint(1,10,(5,6))

In [58]:
arr3

array([[4, 6, 1, 9, 7, 7],
       [2, 1, 8, 6, 6, 6],
       [2, 5, 5, 9, 7, 3],
       [4, 4, 9, 4, 1, 2],
       [8, 2, 5, 3, 4, 6]])

In [59]:
arr3>8

array([[False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [60]:
arr3[arr3>8]

array([9, 9, 9])

In [61]:
#Numpy Array Maninpulation

In [62]:
arr=np.random.randint(1,10,(4,4))

In [63]:
arr

array([[4, 2, 3, 5],
       [9, 8, 4, 1],
       [7, 3, 9, 6],
       [3, 5, 2, 7]])

In [64]:
arr.size

16

In [65]:
arr.reshape(8,2)

array([[4, 2],
       [3, 5],
       [9, 8],
       [4, 1],
       [7, 3],
       [9, 6],
       [3, 5],
       [2, 7]])

In [66]:
arr.reshape(2,8)

array([[4, 2, 3, 5, 9, 8, 4, 1],
       [7, 3, 9, 6, 3, 5, 2, 7]])

In [67]:
arr.T

array([[4, 9, 7, 3],
       [2, 8, 3, 5],
       [3, 4, 9, 2],
       [5, 1, 6, 7]])

In [68]:
arr

array([[4, 2, 3, 5],
       [9, 8, 4, 1],
       [7, 3, 9, 6],
       [3, 5, 2, 7]])

In [70]:
arr.flatten() # it's convert to array in single dimension

array([4, 2, 3, 5, 9, 8, 4, 1, 7, 3, 9, 6, 3, 5, 2, 7])

In [73]:
np.expand_dims(arr,axis=1)

array([[[4, 2, 3, 5]],

       [[9, 8, 4, 1]],

       [[7, 3, 9, 6]],

       [[3, 5, 2, 7]]])

In [74]:
np.expand_dims(arr,axis=0)

array([[[4, 2, 3, 5],
        [9, 8, 4, 1],
        [7, 3, 9, 6],
        [3, 5, 2, 7]]])

In [75]:
data=np.array([[1],[2],[3]])

In [76]:
np.squeeze(data)

array([1, 2, 3])

In [77]:
data

array([[1],
       [2],
       [3]])

In [78]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [79]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [80]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [81]:
#Numpy Binary Operations

In [83]:
arr1=np.random.randint(1,10,(3,3))
arr2=np.random.randint(1,10,(3,3))

In [84]:
arr1

array([[2, 3, 1],
       [9, 1, 1],
       [4, 4, 4]])

In [85]:
arr2

array([[4, 4, 4],
       [9, 8, 6],
       [3, 8, 6]])

In [86]:
arr1+arr2

array([[ 6,  7,  5],
       [18,  9,  7],
       [ 7, 12, 10]])

In [87]:
arr1**arr2

array([[       16,        81,         1],
       [387420489,         1,         1],
       [       64,     65536,      4096]], dtype=int32)

In [88]:
~arr1

array([[ -3,  -4,  -2],
       [-10,  -2,  -2],
       [ -5,  -5,  -5]], dtype=int32)

In [89]:
#Numpy - String Functions

In [90]:
arr=np.array(["sudh","kumar"])

In [91]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [92]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [93]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [94]:
arr1

array([[2, 3, 1],
       [9, 1, 1],
       [4, 4, 4]])

In [95]:
np.sin(arr1)

array([[ 0.90929743,  0.14112001,  0.84147098],
       [ 0.41211849,  0.84147098,  0.84147098],
       [-0.7568025 , -0.7568025 , -0.7568025 ]])

In [96]:
np.cos(arr1)

array([[-0.41614684, -0.9899925 ,  0.54030231],
       [-0.91113026,  0.54030231,  0.54030231],
       [-0.65364362, -0.65364362, -0.65364362]])

In [97]:
np.tan(arr1)

array([[-2.18503986, -0.14254654,  1.55740772],
       [-0.45231566,  1.55740772,  1.55740772],
       [ 1.15782128,  1.15782128,  1.15782128]])

In [98]:
np.exp(arr1)

array([[7.38905610e+00, 2.00855369e+01, 2.71828183e+00],
       [8.10308393e+03, 2.71828183e+00, 2.71828183e+00],
       [5.45981500e+01, 5.45981500e+01, 5.45981500e+01]])

In [99]:
np.mean(arr1)

3.2222222222222223

In [100]:
np.median(arr1)

3.0

In [101]:
np.log10(arr1)

array([[0.30103   , 0.47712125, 0.        ],
       [0.95424251, 0.        , 0.        ],
       [0.60205999, 0.60205999, 0.60205999]])

In [102]:
np.std(arr1)

2.3934065809486684

In [103]:
np.min(arr1)

1

In [104]:
np.max(arr1)

9

In [105]:
np.var(arr1)

5.728395061728396

In [106]:
## Sort,Search & Counting Functions

In [109]:
arr=np.array([2,3,4,5,6])

In [110]:
arr

array([2, 3, 4, 5, 6])

In [111]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [113]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [114]:
arr1=np.array([6,2,14,3,67])

In [115]:
np.sort(arr1)

array([ 2,  3,  6, 14, 67])

In [116]:
np.searchsorted(arr1,6)

2

In [117]:
arr1

array([ 6,  2, 14,  3, 67])

In [118]:
arr2=np.array([0,324,645,65,6,0,0,0,234])

In [119]:
np.count_nonzero(arr2)

5

In [120]:
np.where(arr2>0)

(array([1, 2, 3, 4, 8], dtype=int64),)

In [122]:
np.extract(arr1>2,arr1)

array([ 6, 14,  3, 67])

In [123]:
arr1

array([ 6,  2, 14,  3, 67])

In [124]:
np.extract(arr2>2,arr2)

array([324, 645,  65,   6, 234])

In [125]:
#Numpy - Byte Swapping

In [126]:
arr2

array([  0, 324, 645,  65,   6,   0,   0,   0, 234])

In [127]:
arr2.byteswap()

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
                 0,           0,           0,  -369098752])

In [128]:
arr2

array([  0, 324, 645,  65,   6,   0,   0,   0, 234])

In [129]:
arr2.byteswap(True)

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
                 0,           0,           0,  -369098752])

In [130]:
arr2

array([          0,  1140916224, -2063466496,  1090519040,   100663296,
                 0,           0,           0,  -369098752])

In [131]:
#Numpy Matrix Library

In [132]:
import numpy.matlib as nm

In [133]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [134]:
nm.ones((3,5))

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [136]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [137]:
# Numpy Linear Algebra

In [138]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [139]:
arr1

array([[0, 1],
       [0, 4]])

In [140]:
arr2

array([[3, 1],
       [0, 0]])

In [141]:
np.dot(arr1,arr2)

array([[0, 0],
       [0, 0]])

In [142]:
arr1@arr2

array([[0, 0],
       [0, 0]])