In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [4]:
arr=np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
arr.ndim # ndim tells dimension array

1

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1=np.array([[1,2,3],[2,3,4]])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
mat=np.matrix(l) # matrix have 2d array

In [14]:
mat

matrix([[1, 2, 3, 4, 5]])

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [17]:
np.asanyarray(mat) # matrix as subclass of array

matrix([[1, 2, 3, 4, 5]])

In [18]:
a=arr

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
arr[0]

1

In [21]:
arr[0]=100

In [22]:
arr

array([100,   2,   3,   4,   5])

In [25]:
#copy operation is called as sallow copy

In [26]:
a

array([100,   2,   3,   4,   5])

In [33]:
b=np.copy(arr) # deep copy

In [34]:
b

array([100,   2,   3,   4,   5])

In [35]:
b[0]=234

In [36]:
b

array([234,   2,   3,   4,   5])

In [37]:
arr

array([100,   2,   3,   4,   5])

In [38]:
np.fromfunction(lambda i,j:i==j,(3,3)) #m*n 3 rows and 3 columns

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [42]:
list([i*i for i in range(5)])

[0, 1, 4, 9, 16]

In [51]:
iterable=(i*i for i in range(5))

In [52]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [53]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [54]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [55]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [56]:
arr1.ndim

2

In [57]:
arr1.size

6

In [58]:
arr.size

5

In [59]:
arr.shape

(5,)

In [60]:
arr1.shape

(2, 3)

In [61]:
arr.dtype

dtype('int32')

In [62]:
arr1.dtype

dtype('int32')

In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.arange(.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [5]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [6]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [9]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
arr1=np.zeros((3,4,2))

In [14]:
arr1.ndim

3

In [18]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
arr=np.ones((3,4))

In [22]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [24]:
import pandas as pd

In [25]:
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [26]:
np.random.rand(2,3)

array([[0.31177421, 0.37807999, 0.43091271],
       [0.20363096, 0.20304179, 0.11097875]])

In [28]:
np.random.randn(2,3)

array([[ 0.22317172,  0.73220579, -0.23310876],
       [-0.67202413, -0.44926635, -0.28256624]])

In [29]:
#diff rand ra

In [34]:
arr2=np.random.randint(1,5,(3,4))

In [35]:
arr2

array([[4, 4, 3, 2],
       [2, 3, 2, 2],
       [1, 3, 4, 3]])

In [36]:
arr2.size

12

In [37]:
arr2.shape

(3, 4)

In [38]:
arr2.reshape(12,1)

array([[4],
       [4],
       [3],
       [2],
       [2],
       [3],
       [2],
       [2],
       [1],
       [3],
       [4],
       [3]])

In [39]:
arr2.reshape(6,2)

array([[4, 4],
       [3, 2],
       [2, 3],
       [2, 2],
       [1, 3],
       [4, 3]])

In [40]:
arr2.reshape(4,3)

array([[4, 4, 3],
       [2, 2, 3],
       [2, 2, 1],
       [3, 4, 3]])

In [41]:
arr2.reshape(2,2,3)

array([[[4, 4, 3],
        [2, 2, 3]],

       [[2, 2, 1],
        [3, 4, 3]]])

In [42]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[4]]],


         [[[3]]]],



        [[[[2]]],


         [[[2]]],


         [[[3]]]]],




       [[[[[2]]],


         [[[2]]],


         [[[1]]]],



        [[[[3]]],


         [[[4]]],


         [[[3]]]]]])

In [43]:
arr2=np.random.randint(1,10,(5,6))

In [44]:
arr2

array([[2, 6, 7, 7, 9, 8],
       [3, 6, 2, 3, 7, 1],
       [6, 8, 5, 1, 6, 1],
       [8, 6, 6, 3, 3, 4],
       [1, 1, 4, 4, 6, 1]])

In [45]:
arr2>8

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [46]:
arr2[arr2>8]

array([9])

In [47]:
arr2

array([[2, 6, 7, 7, 9, 8],
       [3, 6, 2, 3, 7, 1],
       [6, 8, 5, 1, 6, 1],
       [8, 6, 6, 3, 3, 4],
       [1, 1, 4, 4, 6, 1]])

In [48]:
arr2.shape

(5, 6)

In [49]:
arr2[0]

array([2, 6, 7, 7, 9, 8])

In [50]:
arr2[0,[0,1]]

array([2, 6])

In [51]:
arr2[2:4,[2,3]]

array([[5, 1],
       [6, 3]])

In [52]:
arr3=np.random.randint(1,3,(3,3))
arr4=np.random.randint(1,3,(3,3))

In [53]:
arr3

array([[2, 1, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [54]:
arr4

array([[2, 2, 2],
       [1, 1, 2],
       [2, 1, 1]])

In [55]:
arr3+arr4

array([[4, 3, 4],
       [2, 3, 3],
       [4, 2, 3]])

In [56]:
arr3-arr4

array([[ 0, -1,  0],
       [ 0,  1, -1],
       [ 0,  0,  1]])

In [57]:
arr3*arr4

array([[4, 2, 4],
       [1, 2, 2],
       [4, 1, 2]])

In [58]:
arr3@arr4

array([[9, 7, 8],
       [6, 5, 7],
       [9, 7, 8]])

In [60]:
arr3/arr4

array([[1. , 0.5, 1. ],
       [1. , 2. , 0.5],
       [1. , 1. , 2. ]])

In [61]:
#Numpy - Broadcasting

In [62]:
arr=np.zeros((3,4))

In [63]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [65]:
a=np.array([1,2,3,4])

In [66]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [74]:
b=np.array([[3,4,5]])

In [75]:
b

array([[3, 4, 5]])

In [76]:
b.T

array([[3],
       [4],
       [5]])

In [77]:
arr+b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [78]:
arr2

array([[2, 6, 7, 7, 9, 8],
       [3, 6, 2, 3, 7, 1],
       [6, 8, 5, 1, 6, 1],
       [8, 6, 6, 3, 3, 4],
       [1, 1, 4, 4, 6, 1]])

In [79]:
arr1

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [80]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
arr3

array([[2, 1, 2],
       [1, 2, 1],
       [2, 1, 2]])

In [83]:
np.sqrt(arr3)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [84]:
np.log10(arr3)

array([[0.30103, 0.     , 0.30103],
       [0.     , 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103]])

In [85]:
np.exp(arr3)

array([[7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [86]:
np.min(arr3)

1

In [87]:
np.max(arr3)

2

In [88]:
import numpy as np

In [89]:
#Numpy - Array Manipulation.

In [90]:
arr=np.random.randint(1,10,(4,4))

In [91]:
arr

array([[9, 1, 7, 6],
       [6, 2, 5, 7],
       [1, 9, 6, 8],
       [8, 3, 9, 8]])

In [92]:
arr.reshape(8,2)

array([[9, 1],
       [7, 6],
       [6, 2],
       [5, 7],
       [1, 9],
       [6, 8],
       [8, 3],
       [9, 8]])

In [93]:
arr.T

array([[9, 6, 1, 8],
       [1, 2, 9, 3],
       [7, 5, 6, 9],
       [6, 7, 8, 8]])

In [95]:
arr.flatten() # Provide one dimension array

array([9, 1, 7, 6, 6, 2, 5, 7, 1, 9, 6, 8, 8, 3, 9, 8])

In [100]:
np.expand_dims(arr,axis=0) #axis=1 column wise | axis=0 row wise 

array([[[9, 1, 7, 6],
        [6, 2, 5, 7],
        [1, 9, 6, 8],
        [8, 3, 9, 8]]])

In [101]:
data=np.array([[1],[2],[3]])

In [102]:
np.squeeze(data)

array([1, 2, 3])

In [103]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [107]:
np.roll(data,4)

array([[3],
       [1],
       [2]])

In [108]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [109]:
#Numpy - Binary Operators

In [110]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [111]:
arr1+arr2

array([[ 9, 16,  7, 11],
       [ 8, 10, 10, 14],
       [ 9, 13,  9,  5]])

In [112]:
arr1-arr2

array([[ 7, -2,  1,  3],
       [-2,  2,  0, -2],
       [-3,  1,  7, -3]])

In [113]:
arr1*arr2

array([[ 8, 63, 12, 28],
       [15, 24, 25, 48],
       [18, 42,  8,  4]])

In [116]:
arr1/arr2

array([[8.        , 0.77777778, 1.33333333, 1.75      ],
       [0.6       , 1.5       , 1.        , 0.75      ],
       [0.5       , 1.16666667, 8.        , 0.25      ]])

In [117]:
arr1-arr2

array([[ 7, -2,  1,  3],
       [-2,  2,  0, -2],
       [-3,  1,  7, -3]])

In [118]:
arr1**arr2

array([[       8, 40353607,       64,     2401],
       [     243,     1296,     3125,  1679616],
       [     729,   117649,        8,        1]], dtype=int32)

In [119]:
~arr1

array([[-9, -8, -5, -8],
       [-4, -7, -6, -7],
       [-4, -8, -9, -2]], dtype=int32)

In [120]:
arr1>arr2

array([[ True, False,  True,  True],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [121]:
# Numpy - String Functions

In [122]:
arr=np.array(["sudh","kumar"])

In [123]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [124]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [125]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [126]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [127]:
## Numpy - Mathematical Functions

In [128]:
np.sin(arr1)

array([[ 0.98935825,  0.6569866 , -0.7568025 ,  0.6569866 ],
       [ 0.14112001, -0.2794155 , -0.95892427, -0.2794155 ],
       [ 0.14112001,  0.6569866 ,  0.98935825,  0.84147098]])

In [129]:
np.cos(arr1)

array([[-0.14550003,  0.75390225, -0.65364362,  0.75390225],
       [-0.9899925 ,  0.96017029,  0.28366219,  0.96017029],
       [-0.9899925 ,  0.75390225, -0.14550003,  0.54030231]])

In [130]:
np.tan(arr1)

array([[-6.79971146,  0.87144798,  1.15782128,  0.87144798],
       [-0.14254654, -0.29100619, -3.38051501, -0.29100619],
       [-0.14254654,  0.87144798, -6.79971146,  1.55740772]])

In [131]:
np.log10(arr1)

array([[0.90308999, 0.84509804, 0.60205999, 0.84509804],
       [0.47712125, 0.77815125, 0.69897   , 0.77815125],
       [0.47712125, 0.84509804, 0.90308999, 0.        ]])

In [132]:
np.exp(arr1)

array([[2.98095799e+03, 1.09663316e+03, 5.45981500e+01, 1.09663316e+03],
       [2.00855369e+01, 4.03428793e+02, 1.48413159e+02, 4.03428793e+02],
       [2.00855369e+01, 1.09663316e+03, 2.98095799e+03, 2.71828183e+00]])

In [133]:
np.power(arr1,2)

array([[64, 49, 16, 49],
       [ 9, 36, 25, 36],
       [ 9, 49, 64,  1]], dtype=int32)

In [138]:
arr1.base

In [139]:
np.mean(arr1)

5.416666666666667

In [140]:
np.median(arr1)

6.0

In [142]:
np.std(arr1)

2.1392496088322392

In [143]:
np.var(arr1)

4.576388888888889

In [144]:
np.min(arr1)

1

In [145]:
np.max(arr1)

8

In [146]:
# Numpy - Arithmetic Operations

In [147]:
arr1

array([[8, 7, 4, 7],
       [3, 6, 5, 6],
       [3, 7, 8, 1]])

In [148]:
arr2

array([[1, 9, 3, 4],
       [5, 4, 5, 8],
       [6, 6, 1, 4]])

In [149]:
arr1-arr2

array([[ 7, -2,  1,  3],
       [-2,  2,  0, -2],
       [-3,  1,  7, -3]])

In [150]:
np.subtract(arr1,arr2)

array([[ 7, -2,  1,  3],
       [-2,  2,  0, -2],
       [-3,  1,  7, -3]])

In [151]:
np.multiply(arr1,arr2)

array([[ 8, 63, 12, 28],
       [15, 24, 25, 48],
       [18, 42,  8,  4]])

In [152]:
np.mod(arr1,arr2)

array([[0, 7, 1, 3],
       [3, 2, 0, 6],
       [3, 1, 0, 1]], dtype=int32)

In [153]:
np.sqrt(arr1)

array([[2.82842712, 2.64575131, 2.        , 2.64575131],
       [1.73205081, 2.44948974, 2.23606798, 2.44948974],
       [1.73205081, 2.64575131, 2.82842712, 1.        ]])

In [155]:
np.power(arr1,2)

array([[64, 49, 16, 49],
       [ 9, 36, 25, 36],
       [ 9, 49, 64,  1]], dtype=int32)

In [156]:
##Numpy Statistical Functions

In [157]:
np.mean(arr1)

5.416666666666667

In [158]:
np.std(arr1)

2.1392496088322392

In [159]:
np.median(arr1)

6.0

In [160]:
## Sort,Search and Counting Functions