In [1]:
## Ask Questions
## Why
## industry use case
## Interview Questions
## Knowledge
## ML model
## Prepare the data with pythom library
## Numpy,Pandas,Seaborn,Matplotlib

# Provides
# 1. An array object of arbitrary homogeneous items
# 2. Fast mathematical operations over arrays
# 3. Linear Algebra, Fourier Transforms, Random Number Generation

# Numpy

### Library - collection of functions,Reusable,Optimised

In [2]:
# Numpy - Numerical python
# Used in data analysis

In [3]:
import numpy as np # 2005 by Travis Oliphant

In [4]:
np.__version__

'1.21.5'

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [6]:
l=[1,2,3,4,5]

In [7]:
arr=np.array(l)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [10]:
#ndarray - n dimentional array 1d,2d,3d,4d ...nd
#array - array is the way numpy stores the data
#it stores only same type of data (homogeneous)

In [11]:
arr.ndim

1

In [12]:
l=[1,2,3,4,5,"Rishi"]
arr1=np.array(l)

In [13]:
arr1

array(['1', '2', '3', '4', '5', 'Rishi'], dtype='<U11')

In [14]:
type(arr1)

numpy.ndarray

In [15]:
arr1.ndim

1

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.ndim

2

In [19]:
l=[1,2,3,4]

In [20]:
np.matrix(l) # matris will be by default 2d

matrix([[1, 2, 3, 4]])

In [21]:
arr3d=np.array([[[1,2],[5,6],[7,8]]])

In [22]:
arr3d

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [23]:
#more way to convert to arry
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [24]:
np.asanyarray([[[1,2],[5,6],[7,8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [25]:
l=[1,2,3,4]
mat=np.matrix(l)

In [26]:
mat

matrix([[1, 2, 3, 4]])

In [27]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [28]:
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [29]:
np.array([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [30]:
t=([1,2,3],[4,5,6])

In [31]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a=5
np.array(a)

array(5)

In [33]:
lst=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [34]:
arr[0:2]

array([1, 2])

In [35]:
a=arr

In [36]:
a

array([1, 2, 3, 4])

In [37]:
arr[0]=1000

In [38]:
arr

array([1000,    2,    3,    4])

In [39]:
a

array([1000,    2,    3,    4])

In [40]:
#shallow copy
#deep copy
#b=a.copy()

In [41]:
#to create arrayb >> .array,.asarray,.asanyarray,deep copy,shallow copy

In [42]:
#There are multiple ways to generating arrays

In [43]:
np.fromfunction(lambda i,j:i==j,shape=(3,3)) #Construct an array by executing a function over each coordinate.

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr1.shape

(2, 3)

In [46]:
arr1.size

6

In [47]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [48]:
range(5)

range(0, 5)

In [49]:
for i in range(0,5):
    print(i)

0
1
2
3
4


In [50]:
[i for i in range(0,5)]

[0, 1, 2, 3, 4]

In [51]:
list((i for i in range(0,5)))

[0, 1, 2, 3, 4]

In [52]:
iterable=(i*i for i in range(5))

In [53]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [54]:
np.fromstring('23 34 67',sep=' ') #sep means separator

array([23., 34., 67.])

In [55]:
np.fromstring('23,34,67',sep=',') #sep means separator

array([23., 34., 67.])

In [56]:
np.fromstring('23,34,67',dtype='int',sep=',')

array([23, 34, 67])

In [57]:
arr.size

4

In [58]:
arr.dtype

dtype('int32')

In [59]:
l=[1,2,3,"khadar"]
arr=np.array(l)
arr.dtype

dtype('<U11')

In [60]:
list(range(5))

[0, 1, 2, 3, 4]

In [61]:
list(range(1,2))

[1]

In [62]:
np.arange(0.1,10.2,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [63]:
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [64]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [65]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
arr3=np.zeros((3,3,4))
arr3.shape

(3, 3, 4)

In [69]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [70]:
arr3.ndim

3

In [71]:
arr4=np.zeros((4,3,4))

In [72]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [73]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [74]:
arr=np.ones((3,4))

In [75]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [77]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [78]:
#Questions
#1. what is numpy
#2.array
#3.difference between list vs array
#4.why array is faster than list ?
#Homogenious
#memory allocation
#-> list -> ["ayay",1,2,3] random allocation of memory will happen
#lists are not stored themselves
#random location,store the address
#list ::concept referencing,resizing

# array
#staically defined not dynamic

#1D - Vector
#2D - matrix
#3D - tensor

#Vectorization


# 21-01-2024

In [79]:
np.empty((3,4)) # returns any random array

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [80]:
np.eye((2)) #a 2-D array with ones on the diagonal and zeros elsewhere.N*N matrix

array([[1., 0.],
       [0., 1.]])

In [81]:
np.eye((2),dtype=int)

array([[1, 0],
       [0, 1]])

In [82]:
#optional

import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [83]:
#extra topics
import random

random.choice((1,2,3,4,5,6))
random.choice('Ajay')
random.randrange(1,1000)
random.random() # a random no is generated between 0 (included),1 well be excluded

lis=[1,2,3,4,5]
random.shuffle(lis)
lis

random.uniform(7,14) # a no between 7 and 14

12.062901090606989

In [84]:
np.random.rand(1)

array([0.33435987])

In [85]:
np.random.rand(2,3)

array([[0.32876246, 0.63589558, 0.38387143],
       [0.33013841, 0.41559444, 0.76830814]])

In [86]:
np.random.uniform(7,14)

8.7261934593927

In [87]:
np.random.rand(2,3)

array([[0.57193948, 0.66674331, 0.22538515],
       [0.67028576, 0.45412929, 0.52724244]])

In [88]:
np.random.random_sample()

0.6980540680150611

In [89]:
arr=np.random.randint(1,5,size=(3,4))

In [90]:
arr.shape

(3, 4)

In [91]:
arr.ndim

2

In [92]:
arr

array([[1, 3, 2, 1],
       [4, 4, 1, 3],
       [1, 3, 2, 2]])

In [93]:
arr.size

12

In [94]:
arr.reshape(2,6) # array size can not change ,multiples of array size

array([[1, 3, 2, 1, 4, 4],
       [1, 3, 1, 3, 2, 2]])

In [95]:
arr.reshape(6,2)

array([[1, 3],
       [2, 1],
       [4, 4],
       [1, 3],
       [1, 3],
       [2, 2]])

In [96]:
arr.reshape(12,1)

array([[1],
       [3],
       [2],
       [1],
       [4],
       [4],
       [1],
       [3],
       [1],
       [3],
       [2],
       [2]])

In [97]:
arr.reshape(3,4)

array([[1, 3, 2, 1],
       [4, 4, 1, 3],
       [1, 3, 2, 2]])

In [98]:
arr.reshape(4,-1) #-1 we don't know the no of columns

array([[1, 3, 2],
       [1, 4, 4],
       [1, 3, 1],
       [3, 2, 2]])

In [99]:
arr.reshape(-1,1)

array([[1],
       [3],
       [2],
       [1],
       [4],
       [4],
       [1],
       [3],
       [1],
       [3],
       [2],
       [2]])

In [100]:
arr

array([[1, 3, 2, 1],
       [4, 4, 1, 3],
       [1, 3, 2, 2]])

In [101]:
arr.reshape(3,4).base

array([[1, 3, 2, 1],
       [4, 4, 1, 3],
       [1, 3, 2, 2]])

In [102]:
arr.reshape(4,3,1)

array([[[1],
        [3],
        [2]],

       [[1],
        [4],
        [4]],

       [[1],
        [3],
        [1]],

       [[3],
        [2],
        [2]]])

In [103]:
arr.reshape(1,1,1,1,1,1,1,1,1,3,4)

array([[[[[[[[[[[1, 3, 2, 1],
                [4, 4, 1, 3],
                [1, 3, 2, 2]]]]]]]]]]])

In [104]:
#lst=

In [105]:
arr2=np.array([[2,3],[4,5]])

In [106]:
arr2

array([[2, 3],
       [4, 5]])

In [107]:
arr2=np.zeros((3,4))

In [108]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
arr2.ndim

2

In [110]:
arr3=np.zeros((1,3,4)) #3 rows,4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [111]:
arr3.ndim

3

In [112]:
arr4=np.zeros((1,1,3,4)) #3 rows,4 columns >> 2d array + 1d +1d

In [113]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [114]:
arr4.shape

(1, 1, 3, 4)

In [115]:
arr4.ndim

4

In [116]:
arr4=np.zeros((2,3,4))

In [117]:
arr4

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [118]:
arr1=np.random.randint(1,10,(5,6))

In [119]:
arr1

array([[1, 3, 1, 8, 3, 3],
       [7, 3, 5, 2, 7, 4],
       [5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6],
       [4, 3, 6, 2, 5, 1]])

In [120]:
arr1>5

array([[False, False, False,  True, False, False],
       [ True, False, False, False,  True, False],
       [False, False, False, False,  True, False],
       [False,  True,  True, False, False,  True],
       [False, False,  True, False, False, False]])

In [121]:
arr1[arr1>5] #

array([8, 7, 7, 7, 6, 7, 6, 6])

In [122]:
arr1[arr1<5]

array([1, 3, 1, 3, 3, 3, 2, 4, 4, 1, 2, 4, 2, 4, 4, 4, 3, 2, 1])

In [123]:
arr1

array([[1, 3, 1, 8, 3, 3],
       [7, 3, 5, 2, 7, 4],
       [5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6],
       [4, 3, 6, 2, 5, 1]])

In [124]:
arr=np.array([1,2,3,4,5])

In [125]:
arr

array([1, 2, 3, 4, 5])

In [126]:
arr1

array([[1, 3, 1, 8, 3, 3],
       [7, 3, 5, 2, 7, 4],
       [5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6],
       [4, 3, 6, 2, 5, 1]])

In [127]:
arr1[0]

array([1, 3, 1, 8, 3, 3])

In [128]:
arr1[0][0]

1

In [129]:
arr1[0][1:3]

array([3, 1])

In [130]:
arr1[0,[1,3]]

array([3, 8])

In [131]:
arr1[2:4]

array([[5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6]])

In [132]:
arr1[2:4,[0,2]]

array([[5, 1],
       [2, 7]])

In [133]:
arr1[2:5]

array([[5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6],
       [4, 3, 6, 2, 5, 1]])

In [134]:
arr1[2:5,[0,1]]

array([[5, 4],
       [2, 6],
       [4, 3]])

In [135]:
arr1[2:5,0:2] #slicing

array([[5, 4],
       [2, 6],
       [4, 3]])

In [136]:
arr1

array([[1, 3, 1, 8, 3, 3],
       [7, 3, 5, 2, 7, 4],
       [5, 4, 1, 2, 7, 4],
       [2, 6, 7, 4, 4, 6],
       [4, 3, 6, 2, 5, 1]])

In [137]:
arr1[2:5,0:2]

array([[5, 4],
       [2, 6],
       [4, 3]])

In [138]:
arr1[[2,4]] # selecting specific column

array([[5, 4, 1, 2, 7, 4],
       [4, 3, 6, 2, 5, 1]])

In [139]:
arr1[2:4,[1,3]]

array([[4, 2],
       [6, 4]])

In [140]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,2,(3,3))

In [141]:
arr1

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [142]:
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [143]:
arr1+arr2

array([[3, 3, 3],
       [2, 2, 3],
       [2, 2, 3]])

In [144]:
arr1*arr2 # index wise multiplication

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [145]:
arr1 @ arr2 # m * n p * q n=p, matrix wise multiplication

array([[6, 6, 6],
       [4, 4, 4],
       [4, 4, 4]])

In [146]:
arr1 / arr2 # index wise divison

array([[2., 2., 2.],
       [1., 1., 2.],
       [1., 1., 2.]])

In [147]:
# Broad casting

In [149]:
arr=np.zeros((3,4))

In [150]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [152]:
a=np.array([1,2,3,4])

In [153]:
a

array([1, 2, 3, 4])

In [155]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [157]:
a

array([1, 2, 3, 4])

In [160]:
a=np.array([[1,2,3]])

In [161]:
a.T

array([[1],
       [2],
       [3]])

In [163]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [165]:
a=np.array([1,2,3])
a.T

array([1, 2, 3])

# mathematical functions

In [167]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [168]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.30103],
       [0.     , 0.     , 0.30103]])

In [169]:
np.exp(arr1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ]])

In [170]:
np.min(a)

1

In [171]:
np.max(arr1)

2

In [172]:
arr1

array([[2, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [173]:
arr1.T

array([[2, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [174]:
arr1.flatten() # reduce higher dimension to 1D

array([2, 2, 2, 1, 1, 2, 1, 1, 2])

In [175]:
#expand_dims >> expands the array by inserting a new axis

In [176]:
# axis=0 row wise axis=1 column wise

In [180]:
arr=np.array([[1,2,3],[4,5,6],[1,2,3]])

In [181]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [182]:
np.sum(arr)

27

In [185]:
np.sum(arr,axis=0) # row wise but its calculating column wise

array([ 6,  9, 12])

In [186]:
np.sum(arr,axis=1) # column wise but its calculating rouw wise

array([ 6, 15,  6])

In [187]:
#expand_dims >> expand the dimentsion of array

In [188]:
arr=np.array([1,2,3,4])

In [189]:
arr.ndim

1

In [191]:
arr

array([1, 2, 3, 4])

In [194]:
arr1=np.expand_dims(arr,axis=0)

In [196]:
arr1.ndim

2

In [197]:
arr2=np.expand_dims(arr,axis=1)

In [198]:
arr2

array([[1],
       [2],
       [3],
       [4]])

In [199]:
arr=np.zeros((3,4))

In [200]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [201]:
arr1=np.expand_dims(arr,axis=1)

In [202]:
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [205]:
arr1.ndim

3